### ISSUE TITLE
Singleplayer compatability

### ISSUE THREAD

**Issue by olillin** [olillin/bonk#1]
Currently the mod sometimes doesn't work in singleplayer. Most notably:

- Sounds sometimes don't play
- The mace does nothing

**Comment by olillin** [comment]
Fixed by 17f91ff587c1d4e6b0f27fc5f6c8cf0920790d2c

**Comment by MarcPG1905** [comment]
The mace is still not working for me. It doesn't deal damage to the villager, but doesn't reset its trades either. Using the latest Modrinth version for 1.21.1!

**Comment by olillin** [comment]
@MarcPG1905 The latest version of the mod only supports 1.21.3, not 1.21.1. You shouldn't even be able to launch the game with 1.21.1, are you sure that's the version you are using?

**Comment by olillin** [comment]
Closing this as I cannot replicate the issue
